# Generated by Django 4.2.4 on 2023-08-18 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_comment_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="comments",
            field=models.IntegerField(default=0),
        ),
    ]
